coala/landing-frontend

index.html

Fixes https://github.com/coala/landing-frontend/issues/5

index.html: Update path to jquery

---

resources/js/config.js

Fixes https://github.com/coala/landing-frontend/issues/8

config.js: Add link to web service

---

resources/js/config.js

Fixes https://github.com/coala/landing-frontend/issues/13

config.js: Change http to https

---

partials/tabs/home.html

People told me they don't like it. I agree.

home: Remove sentence

---

partials/tabs/home.html
resources/css/style.css

home: Reindent source code

---

index.html
partials/tabs/home.html
resources/css/style.css
resources/js/app.js

Fixes https://github.com/coala/landing-frontend/issues/12

style.css: Add responsiveness

---

partials/tabs/getinvolved.html
resources/css/style.css
resources/js/app.js

Fixes https://github.com/coala/landing-frontend/issues/31

app.js: Show contributor data from all repositories

---

resources/js/app.js

Closes: https://github.com/coala/landing-frontend/issues/36

app.js: Path correction

---

partials/tabs/home.html
resources/css/style.css

Closes: https://github.com/coala/landing-frontend/issues/34

Fix issue 34

---

README.md

Fixes https://github.com/coala/landing-frontend/issues/38

README.md: Add local deployment instructions

---

index.html
partials/tabs/tryonline.html
resources/css/style.css

index.html: Add beta badge and remove redundant heading

---

resources/css/style.css

Fixes https://github.com/coala/landing-frontend/issues/50

style.css: Improve line-height and height of badge

---

resources/css/style.css

Fixed https://github.com/coala/landing-frontend/issues/16

style.css: Change cursor on tabs and cards

---

partials/tabs/languages.html

Closes https://github.com/coala/landing-frontend/issues/65
CC @underyx more commits coming

languages: Remove explore button

---

partials/tabs/languages.html
resources/css/style.css

wrt e8af204
Languages aligned to bottom
wrt 	9bd089a
restructuredText rendering

style.css: Give fixed height to bear cards

---

partials/tabs/home.html
resources/css/style.css

wrt 	00ed2a4
wrt 	bc7659d 7ec4f93

style.css: Increase height of snippets code container

---

partials/tabs/home.html

Replace the uppercase L with lowercase l
Fixes https://github.com/coala/landing-frontend/issues/82

home.html: Linting use lower case l

---

includes/footer.html

footer.html: Code of Conduct link added
Closes https://github.com/coala/landing-frontend/issues/91

footer.html: Adding CoC link

---

.coafile
.gitignore
partials/tabs/getinvolved.html
partials/tabs/languages.html
partials/tabs/tryonline.html
resources/css/style.css
resources/js/app.js

languages.html: Add settings section

---

partials/tabs/home.html
resources/css/style.css

Contact details added below the installation
section

head.html: Add note of support

---

README.md
partials/tabs/getinvolved.html

Closes https://github.com/coala/landing-frontend/issues/124

getinvolved.html: Sort by reviews

---

partials/tabs/getinvolved.html
resources/css/style.css

Improved readability of getInvolved section by left aligning the first paragraph of this section.
Also, underlined the links on hover.
Fixes #79

style.css: Improve readability of "Get Involved" section

---

partials/tabs/getinvolved.html
resources/js/app.js

Added a filter in order to move null review count
to the bottom of the list. The filter can be found
here : http://stackoverflow.com/a/27963602

Fix null reviews on sorting by reviews

---

data/snippets/yaml.md
resources/js/snippets.js

snippets: Add YAML

---

partials/tabs/languages.html
resources/css/style.css

Closes https://github.com/coala/landing-frontend/issues/119
them.
instead. …

style.css : make search bar placeholder visible in all browser + styling

---

resources/css/style.css

- Add left padding to search box
- Left align text and placeholder in search bar
<br><br>
On Click
them. …

style.css: Styling changes in search bar

---

resources/css/style.css

Closes https://github.com/coala/landing-frontend/issues/140
them.
instead. …

style.css: Align get-involved description to center

---

index.html

This will remove horizontal scrolling bug in
'Try Online' section
them. …

index.html: Add container class to ng-view div

---

resources/css/style.css

style.css: Change cursor to pointer on available bears link
The link for available bears does not look clickable at first. These changes ensure user-friendliness.
Current version : 
After this PR : 
Closes https://github.com/coala/landing-frontend/issues/150
them.
likely receive a lot of bot comments and build failures if coala does …

style.css: Change cursor to pointer on available bears link

---

.coafile
resources/css/style.css

.coafile: Add IndentationBear, indent style.css
As pointed out in the gitter channel, the formatting in style.css
was  mixed up.
This PR corrects my previous unintended commit. 
Closes #97 
them.
After you submit your pull request, …

.coafile: Add IndentationBear, indent style.css

---

partials/tabs/home.html

Closes https://github.com/coala/landing-frontend/issues/154
them.
instead. …

home: Simplify and add editor plugins

---

index.html
partials/tabs/about.html
resources/css/style.css
resources/js/Directives/aboutDirective.js
resources/js/app.js

project: Add about page

---

partials/tabs/about.html
partials/tabs/languages.html
resources/css/style.css

about.html: Add content in cards

---

resources/js/Directives/getinvolvedDirective.js

Exclude rultor and gitmate-bot
Fixes https://github.com/coala/landing-frontend/issues/129
them. …

getinvolvedDirective.js: Exclude bots

---

partials/tabs/coalaonline.html
resources/js/Directives/coalaOnlineDirective.js

Closes https://github.com/coala/landing-frontend/issues/186
them.
instead. …

coalaOnline: Add support for git repository linting

---

partials/tabs/coalaonline.html

coalaonline: Show file name in git mode

---

partials/tabs/home.html

Made Sublime to Sublime Text
Closes https://github.com/coala/landing-frontend/issues/162
them. …

home.html: Typo

---

partials/tabs/coalaonline.html
partials/tabs/languages.html
resources/js/Directives/coalaOnlineDirective.js
resources/js/app.js

coalaOnline: Add support for optional settings

---

data/people/gitmate.md
data/people/hemang.md
data/people/lasse.md
index.html
partials/tabs/people.html
resources/css/people.css
resources/js/Directives/peopleDirective.js
resources/js/app.js

people: Add support for personal links

---

data/people/zimmermann.md

@hemangsk Let there be `social: bitbucket:` please :)
And could we quickly make `coala.io/bearship` available? I wanna try to get it into a presentable state for a lightning talk on Sunday @ **PyConPL**
cc @sils

people: Add zimmermann

---

partials/tabs/people.html
resources/css/people.css

people: Add markdown support in bio

---

data/people/zimmermann.md

people/zimmermann: Add facebook & instagram links

---

partials/tabs/languages.html

Closes coala/landing-frontend#224
them.
instead.
Please consider helping …

languages.html: Change Non Optional to Mandatory

---

partials/tabs/about.html

Changed 'click here' to 'click below' because it was not
directing to any link.
Fixes #222
them. …

about.html: Change statement to right direction

---

partials/tabs/about.html

The link pointed to http://coala.io/#!/languages, it now points to
https://coala.io/#/languages.
Closes https://github.com/coala/landing-frontend/issues/232
- [ x] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
pass on every …

about.html: Fix link to point to bears docs

---

partials/tabs/home.html

home.html: Wrap --pre in a  code tag

---

data/snippets/haml.md
resources/js/snippets.js

data/snippets : Add code snippet for HAML  

---

partials/tabs/languages.html
resources/js/Directives/languagesDirective.js

This commit allows filtering languages on clicking the labels
Closes #230
them. …

languagesDirective.js: Add filtering of languages

---

partials/tabs/home.html

Added description regarding versions of Python and pip required to install coala at [Home Page](https://coala.io/#/home)
[#4973](https://github.com/coala/coala/issues/4973)
them.
After you submit your pull request, **DO NOT click …

Landing frontend testing

---

data/snippets/lua.md
resources/js/snippets.js

snippets: Add Lua

---

ISSUE_TEMPLATE.md

Added ISSUE_TEMPLATE

---

index.html

Fixes https://github.com/coala/landing-frontend/issues/263
them.
instead. …

Changed cOALA to coala

---

resources/js/snippets.js

This makes the dropdown list alphabetical
Closes https://github.com/coala/landing-frontend/issues/276
them. …

snippets.js: Move Lua snippet to follow JSON

---

data/snippets/java.md
resources/js/snippets.js

Add Java example in "get started"

---

partials/tabs/coalaonline.html

This changes the font of the "Add Bear" button on Coala Online
from Times New Roman to Roboto.
Closes https://github.com/coala/landing-frontend/issues/270
them.
After you submit your pull request, **DO NOT click the 'Update Branch' …

coalaonline.html: Change "Add Bear" button font to Roboto

---

partials/tabs/home.html
resources/js/app.js

Add lang parameter to the URL
Fixes https://github.com/coala/landing-frontend/issues/277
them. …

Make code examples on homepage bookmarkable
